Main Review
gudleyd/RedditCommentsScrapper pull request #1
Opened 2021-07-04 13:56 UTC by gudleyd

2021-07-04 14:22 UTC, petuhovskiy commented
Начну с кодстайла. В го есть линтер https://golangci-lint.run , им пользуются примерно все. По дефолту у него неплохие настройки, можно запустить `golangci-lint run` прямо в репо и он покажет все плохое что найдет.

Также у него есть опция `golangci-lint run --fix`, которая сама исправит всё что сможет, в том числе запустит gofmt и проставит переводы строк где нужно, и так далее. Рекомендую поставить себе golangci-lint и сразу запустить fix из корня репо. Это отформатирует файлы где нужно и устранит большинство проблем.

2021-07-04 14:24 UTC, petuhovskiy commented on Dockerfile
> +COPY config.json /run
Копировать конфиги в образ не очень, потому что в этом случае для обновления конфига нужно либо пересобирать контейнер, либо монтировать файл конфига, что неудобно. Я бы сделал конфиг полностью в ENV, но про это еще напишу позже.

2021-07-04 14:24 UTC, petuhovskiy commented on Dockerfile
> +ENTRYPOINT ["./redditbot"]
Обычно в unix принято ставить \n в конце любого текстового файла, так будет аккуратнее.

2021-07-04 14:27 UTC, petuhovskiy commented on docker-compose.yml
> +      - "5432:5432"
Не критично, но кажется постгрес наружу здесь не обязательно открывать.

2021-07-04 15:10 UTC, petuhovskiy commented
Насчет пакетов в го и организации кода.

Сейчас все находится в одном пакете, что нормально при старте проекта, но обычно быстро становится неудобно. Как мне кажется, система пакетов в Go это одно из главных отличий Go от традиционных языков, и то, с чем возникает больше всего трудностей. Ключевое отличие в том, что в Go пакеты не могут образовывать циклические зависимости, и поэтому нужно думать над организацией пакетов гораздо больше чем в других языках.

Сейчас все находится в пакете main, и проблема здесь в том, что пакет main нельзя переиспользовать. Во-первых, это основной пакет с точкой входа из которого идут все зависимости, и любой пакет который будет использовать main не сможет вызываться из main. Во-вторых, сам го скорее всего не даст его заимпортить.

Пусть здесь и небольшой проект, но я бы все равно попробовал разнести все по пакетам. Пакеты скорее всего получатся совсем маленькие, но в этом нет проблемы. Я бы предложил такую структуру:

- main (/) -> (*). Пакет main в корне репозитория, с одним коротким файлом main.go, который ссылается на все остальные пакеты и связывает весь код.
- config (/config) -> (). Пакет в котором объявлена структура конфига и есть функция для его чтения. На него скорее всего будут ссылаться все остальные пакеты.
- mylog? (/mylog?) -> (). Пакет с функцией Logf для логов. На него тоже будут ссылаться все остальные. Я вижу что есть свой примитивный логгер в виде функции `Logf`, что в целом ок, главное чтобы он использовался для всех логов. А если хотелось просто ставить в логах свой префикс, то можно было юзать https://golang.org/pkg/log/#SetPrefix и другие опции стандартного логгера. Что касается названия пакета, лучше выбрать отличное от "log", чтобы не было проблем в IDE при разработке. Также можно просто взять готовый логгер https://github.com/sirupsen/logrus , в нем есть поддержка уровней, и он достаточно удобный.
- db (/db) -> (config, log, models). Пакет для всего, связанного с работой с базой. Скорее всего ему нужны будут пакеты для конфига и логов. В этом пакете логично заниматься подключением к базе, миграцией схемы бд, а также сделать структуру CommentRepo с функцией Save(comment), и возможно что-то еще. Модели тоже можно поместить в этот пакет, но лучше в отдельный.
- models (/models) -> (). Пакет со структурами для моделей, без лишних зависимостей.
- logic (/logic) -> (config, log, db, models). Пакет с основной логикой, такой как сохранение новых комментов в базе (вызвать db.CommentRepo.Save) и общение с реддитом.
- handlers (/handlers) -> (config, log, db, logic, models). Пакет с хандлерами, парсит запросы, и запускает нужную логику в других пакетах.


Это структура для примера, у тебя может быть и другая. Одно из самых важных свойств такой организации, что все кроме main можно как-то изолировать, подменить или протестировать.

2021-07-04 15:12 UTC, petuhovskiy commented on src/comments-observer.go
> +	if c.db.Model(&newComment).Where("full_name = ?", newComment.FullName).Count(&count); count == 0 {
Лучше это вынести в отдельную функцию 

```golang
type CommentRepo struct {
   db *gorm.DB
}

func (c *CommentRepo) Upsert(c models.Comment) error {
    // ...
}
```

2021-07-04 15:14 UTC, petuhovskiy commented on src/config.go
> +	file, _ := os.Open("config.json")
Все ошибки нужно обрабатывать и либо пропускать наверх `return nil, err`, либо правильно обрабатывать (например log.Fatal, log.Error итд). Терять ошибки не имеет смысла почти никогда.

2021-07-04 15:15 UTC, petuhovskiy commented on src/config.go
> +		panic("Configuration file is not parseable")
panic (почти) никогда не стоит использовать. В этом проекте точно не нужно, а вот `return err` вполне ок.

2021-07-04 15:17 UTC, petuhovskiy commented on src/log.go
> +	fmt.Print(LogLevelColor[level])
Три последовательных принта не выглядят атомарно, лучше было бы:

```golang
fmt.Print("%s"+format+"%s", prefix, a..., suffix)
```
```

2021-07-04 15:17 UTC, petuhovskiy commented on src/main.go
> +		panic("Failed to create bot handle")
Как писал выше, нехорошо терять ошибки, а также нехорошо паниковать.

2021-07-04 15:19 UTC, petuhovskiy commented on src/main.go
> +	router := httprouter.New()
httprouter не выглядит очень полезным, потому что все что здесь используется есть в стандартном https://golang.org/pkg/net/http/#NewServeMux

Можно просто заменить код на него почти 1в1.

2021-07-04 15:21 UTC, petuhovskiy commented on src/main.go
> +	router.GET("/start_observing/:subredditName", Handler{config, db, &bot}.StartObserving)
handler лучше один раз создать до этого.

```golang
handler := handlers.NewHandler(config, db, bot)
handler.StartObserving
handler.StopObserving
```

2021-07-04 15:22 UTC, petuhovskiy commented on src/observing.go
> +	db.Find(&subredditsToObserve)
В gorm тоже нужно обрабатывать ошибки, но через чуть менее очевидный синтаксис.

```golang
err := db.Find(&subredditsToObserve).Error
if err != nil {
   return err
}
```

2021-07-04 15:24 UTC, petuhovskiy commented on src/observing.go
> +func SubredditCommentsPreload(subredditName string, config Configuration, db *gorm.DB) {
golangci-lint скорее всего в этом месте скажет что функция слишком большая и когнитивно-сложная, и я в этом месте с ним соглашусь.

Скорее всего здесь можно сделать несколько вспомогательных функций рядом, и так получится более читабельный код.

2021-07-04 15:26 UTC, petuhovskiy requested changes
Все круто, но было бы неплохо обрабатывать ошибки :)
Про структуру пакетов написал выше, очень рекомендую попробовать раскидать код по пакетам.

2021-07-04 15:34 UTC, petuhovskiy commented
Ну и еще, через GitHub Actions можно легко подключить в CI запуск сборки в докере и линтера golangci-lint. Вот пример https://github.com/petuhovskiy/go-template/tree/master/.github/workflows , кажется заработает даже если просто скопировать файлы к себе в репозиторий один в один.

2021-07-04 19:33 UTC, gudleyd commented on src/main.go
> +	router := httprouter.New()
Тут все таки выбираю остаться на httprouter

2021-07-04 21:11 UTC, petuhovskiy commented on src/config.go
> +func GetConfig() Configuration {
По поводу конфига, я с https://12factor.net/config отдаем предпочтение конфигу в environment variables. Конфиг в env проще менять и передавать в контейнеры и приложения. Также с конфигом забитым в файле config.json будет сложно запустить несколько приложений с разным конфигом одновременно.

Для чтения конфига из env можно использовать либу http://github.com/caarlos0/env , в которой теги будут указываться почти точно так же как и в json. Плюсом является то, что в тегах можно указать и значения по умолчанию, и тогда можно будет вообще не передавать никакой конфиг в большинстве случаев.

2021-07-04 21:12 UTC, petuhovskiy commented on src/main.go
> +	bot, botErr := reddit.NewBotFromAgentFile("scrapper.agent", 0)
Было бы круто, если бы конфиг скраппера читался не из файла, а тоже брался из env, чтобы в контейнер не нужно было тащить вообще никаких левых файлов.

2021-07-05 13:20 UTC, petuhovskiy requested changes
Я напутал немного с golangci-lint, у него сейчас по дефолту мало чего включено, поэтому он не отформатировал код и почти ничего не сделал. Я добавил нужных линтеров, получилась такая команда для запуска:

```bash
golangci-lint run -p bugs,comment,complexity,error,format,import,metalinter,style,unused -D wsl,forbidigo,nlreturn,exhaustivestruct,wrapcheck 
```

Теперь он выдает нормальные замечания, я бы сказал что 90% по делу. Как говорил раньше, лучше сразу дописать в конец `--fix` и он пофиксит форматирование.

2021-07-05 13:33 UTC, petuhovskiy commented on Dockerfile
> +RUN go build -o redditbot .
Неудобно как-то для каждой папки COPY добавлять)

Я бы так сделал:

```Dockerfile
COPY go.mod go.sum .
RUN go mod download

COPY . .
RUN go build -o redditbot .
```

- WORKDIR указан, поэтому `/build` можно на `.` заменить
- Лучше сначала скачать зависимости, а потом скопировать код, чтобы работал [кеш](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#leverage-build-cache)
- Можно скопировать сразу всю папку, потому что она все равно не пойдет в результирующий контейнер (который в этапе run), а в контекст все равно копируется. Если не хочется какие-то файлы копировать, то их по аналогии с `.gitignore` нужно добавить в `.Dockerignore`

2022-11-10 01:50 UTC, merged